version: 2

sources:
  - name: stage
    schema: stage

    tables:
      - name: users
      - name: organizations
      - name: tickets
        loaded_at_field: created_at

        freshness:
          warn_after: {count: 100, period: day}
          error_after: {count: 200, period: day}